### ISSUE TITLE
Making `storechain` public

### ISSUE THREAD

**Issue by FjolleJagt** [mindriot101/rust-emcee#21]
Hi,

I'm trying to use your (great!) crate on quite a large model: ~2500 parameters, 25000 walkers and 100 iterations. This means that emcee tries to reserve a very large amount of memory (~50GiB if I remember correctly) and crashes at the end of the first iteration.

I see you have a `storechain` variable on EnsembleSampler which is not public (but does have an associated test): setting this to false fixes the problem.

Is there a reason it's not public? If not, then I can put together a patch documenting the variable and making `storechain` public.

Best wishes,
Josh

**Comment by mindriot101** [comment]
Hi, thanks for your interest in my crate!

That's a huge model! Have you tried using the python version? Just for my curiosity you understand, I would hope the Rust version would be more efficient :P

You're right, it is private (I don't think with a good reason) and if you've found it useful then I'm happy to expose it with some documentation. I would think a method name like:

```rust
sampler.store_chain(true);
```

If you're happy to put together a patch then I'd welcome the contribution, thank you!

**Comment by FjolleJagt** [comment]
I'm afraid I haven't tried the python version, no.

Sure, I'll put together a patch when I have time, probably on the weekend.

**Comment by FjolleJagt** [comment]
Also, `thin` is currently exposed as just a pub field on the struct: would you rather just make the field `storechain` public? It doesn't feel like having a setter method gains you much here unless e.g. you expect to change the way you internally represent the sampler's settings.

**Comment by mindriot101** [comment]
You're absolutely right, i'm happy to just expose the member variable to be public. Could you implement this and check that the tests pass?
